
#### general settings

name: 01_FIRN_DB_x4_scratch_DF2K
use_tb_logger: true
model: FIRN
distortion: sr
scale: 4
gpu_ids: [0]


#### datasets

datasets:
  train:
    name: DF2K
    mode: LQGT
    dataroot_GT: 'C:\Users\Administrator\Downloads\Invertible-Image-Rescaling-master\Invertible-Image-Rescaling-master\codes\datasets\DF2K\DF2K'
    dataroot_LQ: ~ # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_set14
    mode: LQGT
    dataroot_GT: 'C:\Users\Administrator\Downloads\Invertible-Image-Rescaling-master\Invertible-Image-Rescaling-master\codes\datasets\val_set14_part\Set14'
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8, 8]
  scale: 4


#### path

path:
  pretrain_model_G: ~
  pretrain_model_D: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  niter: 50000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [100000, 200000, 300000, 400000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: charbonnier

  manual_seed: 10

  val_freq: 1000

  lambda_fit_forw: 16.
  lambda_rec_back: 0.0628
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10


#### logger

logger:
  print_freq: 50
  save_checkpoint_freq: 10000
